### ISSUE TITLE
Feature request: Use service type Nagios, not Generic Events API

### ISSUE THREAD

**Issue by chrisgagne** [itsjohannawren/pd-nag-connector#5]
Request: Modify the script so that it's set up to work with services of type Nagios, not Generic API. https://github.com/jeffwalter/pd-nag-connector/blob/master/pagerduty.cgi this script that interprets our webhooks would need to be modified to handle the Nagios service type.

**Comment by itsjohannawren** [comment]
Like I mentioned at lunch today, I'm sending an incident ID from the connector that maps back to the problem ID in Nagios. Because the PagerDuty Nagios API doesn't support this I can't use it.
